# Generated by Django 3.1.7 on 2021-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billmodel',
            fields=[
                ('donor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=9)),
                ('gender', models.CharField(max_length=1)),
                ('donated_amount', models.FloatField()),
                ('prev_donated', models.BooleanField()),
            ],
            options={
                'db_table': 'donortable',
            },
        ),
    ]
