# Generated by Django 3.1.7 on 2021-05-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='c_image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billmodel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
